# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Yashaswini Ramasheshu
first_name: Yashaswini
middle_name: 
last_name: Ramasheshu
email: yashaswini.r.bharadwaj@gmail.com

# No spaces before these lines!
url: https://yashaswiniramashesh.github.io
baseurl: ""

description: >
  AI Engineer II, Scalence <br>
  Sunnyvale, CA, USA
